### ISSUE TITLE
Overflow in query input including user ID in PostgreSQL

### ISSUE THREAD

**Issue by star0202** [team-crescendo/Crenata#39]
![image](https://github.com/team-crescendo/Crenata/assets/61998307/8d2901da-fb83-4af4-a310-0ef634764107)

**Comment by bluefcat** [comment]
overflow나는거가 sqlalchemy 2.0 마이그레이션 후에 발생 -> sqlalchemy 2.0 후에 버그수정함 -> overflow 버그 고쳐야지 버그수정 커밋 가져올 수 있음
