### ISSUE TITLE
ModuleNotFoundError: No module named 'aiosqlite'

### ISSUE THREAD

**Issue by star0202** [team-crescendo/Crenata#4]
[sqlalchemy/.../aiosqlite.py](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4/lib/sqlalchemy/dialects/sqlite/aiosqlite.py#L321)에서 `aiosqlite` 모듈을 필요로 하지만, 어떤 이유로 설치되지 않은 듯 합니다..

OS: Windows 11 Pro
IDE: Pycharm Professional 2022.3.2
Python: 3.11 (venv)

재현:
```pwsh
python -m venv .venv
./.venv/scripts/activate
pip install -U setuptools
pip install poetry
poetry install
python -m crenata --config "컨피그 파일"
```

해결:
```pwsh
poetry add aiosqlite
```

**Comment by SaidBySolo** [comment]
의도된것입니다.

Crenata는 [PostgreSQL](https://www.postgresql.org/)을 사용합니다.

aiosqlite는 개발 목적을 위해 사용되며 종속성에 추가되는것을 원치 않습니다.

**Comment by star0202** [comment]
그럼 dev dependency를 따로 추가하거나 [docs/README.md](https://github.com/team-crescendo/Crenata/blob/docs/docs/README.md)에 안내문을 추가해주실 수 있나요?

**Comment by star0202** [comment]
e506cecb04f7ca1748a00c82b7d9cf9cbe502213

**Comment by star0202** [comment]
헉 죄송합니다 PR이랑 링크가 되는지 몰랐네요
