### ISSUE TITLE
Windows에서의 UnicodeEncodeError

### ISSUE THREAD

**Issue by star0202** [team-crescendo/Crenata#7]
## 환경
- Windows
## 내용
[utils/datetime.py](https://github.com/team-crescendo/Crenata/blob/main/crenata/utils/datetime.py#L41)에서 UnicodeEncodeError가 발생합니다
## 재현
Windows 환경에서 datetime.strftime()의 매개변수에 한글을 포함하는 문자열 작성

모바일에서 작성해 가독성에 문제가 있을 수 있습니다

**Comment by SaidBySolo** [comment]
재현할 수 없습니다.

자세한 정보를 제공해주실수 있으신가요?

**Comment by star0202** [comment]
운영체제: Windows 11 Pro (22H2)
Python: 3.10.10
재현 명령어:
```pwsh
poetry run pytest --asyncio-mode=auto
```
오류:
```py
date = datetime.datetime(2021, 1, 1, 0, 0)

    def datetime_to_readable(date: datetime) -> str:
        """
        datetime을 YYYY년 MM월 DD일 형식의 문자열로 변환합니다.
        """
>       return date.strftime("%Y년 %m월 %d일")
E       UnicodeEncodeError: 'locale' codec can't encode character '\ub144' in position 2: encoding error

crenata\utils\datetime.py:41: UnicodeEncodeError
```

**Comment by star0202** [comment]
https://stackoverflow.com/questions/16034060/python3-datetime-datetime-strftime-failed-to-accept-utf-8-string-format

**Comment by SaidBySolo** [comment]
다음 코드블록의 실행결과를 보여주실수 있으신가요?

```py
import locale
locale.getdefaultlocale()
locale.getlocale()
```

**Comment by star0202** [comment]
음 지금 모바일이여서 확인은 불가능하지만
제 노트북 locale이 영어였던 게 문제로 보이네요

**Comment by SaidBySolo** [comment]
```py
>>> import locale
>>> locale.getdefaultlocale()
('ko_KR', 'cp949')
>>> locale.getlocale()
('Korean_Korea', '949')
```

조사해본결과  ``locale.getlocale()`` 를 호출했을때 ``('Korean_Korea', '949')`` 다음과 같은 값이 아닐경우 해당 오류가 raise되는것을 확인할수 있었습니다.

유저 개인의 설정 문제로 보입니다.
